version: '2.0'
services:
  nest_graphql:
    container_name: nest_api_graphql
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/api
  database:
    container_name: nest_db_graphql
    image: 'postgres:13'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432